### ISSUE TITLE
Print Error

### ISSUE THREAD

**Issue by TTomme** [SeanMcGrath/poshmark-crawler#2]
I am very new to Python - so likely something I do not understand - but I get the following error when I try to run crawl.py

P:\POSH_McGrathAuto>cmd
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

P:\POSH_McGrathAuto>crawl.py
  File "P:\POSH_McGrathAuto\crawl.py", line 26
    print 'starting crawl'
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('starting crawl')?

P:\POSH_McGrathAuto>

**Comment by SeanMcGrath** [comment]
Looks to me like you're trying to run this script with Python 3. Python 3 defines `print` as a function, which you have to call with parentheses. You should use Python 2 instead, which defines `print` as a keyword which doesn't need parentheses.
